services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: devboard
      POSTGRES_PASSWORD: devboard
      POSTGRES_DB: devboard
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d devboard"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"

  backend:
    image: 621541294561.dkr.ecr.us-east-1.amazonaws.com/devops-todo:backend-v0001
    container_name: backend
    environment:
      PORT: 8080
      POSTGRES_URL: postgres://devboard:devboard@postgres:5432/devboard?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "8000:8080"

  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: 621541294561.dkr.ecr.us-east-1.amazonaws.com/devops-todo:frontend-v0001
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8080:4173"

volumes:
  postgres_data: